media:
  input: "src/assets"
  output: "src/assets"

content:
  - name: kb
    label: Posts
    path: src/content/kb
    type: collection
    fields:
      - name: isDraft
        label: Is Draft
        type: boolean
        default: false
        required: true
      - name: publishDate
        label: Publish Date
        type: date
        required: true
      - name: updatedDate
        label: Updated Date
        type: date
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: image
        label: Image
        type: image
      - name: excerpt
        label: Excerpt
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
        required: true
